services:
  wazuh.agent:
    container_name: wazuh.agent-pruebas
    image: wazuh/wazuh-agent:4.14.1
    restart: always
    #deploy:
    #  resources:
    #    limits:
    #      memory: 1G
    #      cpus: "2.0"
    #    reservations:
    #      memory: 512M
    #      cpus: "1.0"
    environment:
      - WAZUH_MANAGER_SERVER=wazuh.manager
      - WAZUH_AGENT_NAME=localhost
      - WAZUH_MANAGER_SERVER_PORT=1514
      - TZ=America/Costa_Rica
    volumes:
      - ./conf/ossec.conf:/var/ossec/etc/ossec.conf
      - ./var/lib/docker/containers:/var/lib/docker/containers:ro
      - /:/host:ro
      #- /proc:/proc:ro
      #- /sys:/sys:ro
      #- /dev:/dev:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- /proc/meminfo:/host_proc_meminfo:ro
    #depends_on:
    #  - wazuh.manager
