services:
  wazuh.agent:
    #image: wazuh/wazuh-agent:4.14.5
    build:
      context: .
      dockerfile: Dockerfile
    image: simovilab/wazuh-agent-docker:4.14.5
    restart: always
    container_name: wazuh.agent
    hostname: $LOCAL_AGENT_HOSTNAME
    privileged: true
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "2.0"
        reservations:
          memory: 512M
          cpus: "1.0"
    #user: "1001:990"
    group_add:
      - "${DOCKER_GID}"
    environment:
      - WAZUH_MANAGER_SERVER=${REMOTE_AGENT_MANAGER_SERVER}
      #- WAZUH_AGENT_NAME=localhost
      - WAZUH_MANAGER_SERVER_PORT=1514
      - TZ=${TZ}
    volumes:
      - ../${SCRIPT_POST_INSTALL}:/init_01.sh:ro
      - ../config/wazuh_cluster/authd.pass:/var/ossec/etc/authd.pass
      - ./conf/ossec.conf:/var/ossec/etc/ossec.conf
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /etc/os-release:/etc/os-release:ro
      #- /sys:/sys:ro
      #- /etc:/host/etc:ro
      #- /var/run:/var/run
      #- /sys:/sys:ro
      #- /proc:/proc:ro
      #- /proc:/proc:ro
      #- /dev:/dev:ro
      #- /proc/meminfo:/host_proc_meminfo:ro
    entrypoint: ["/init_01.sh", "${REMOTE_AGENT_MANAGER_SERVER}"]
    #depends_on:
    #  - wazuh.manager 
